files:
  - source: /udata_gouvfr/translations/udata-gouvfr.pot.@@
    translation: /udata_gouvfr/translations/%two_letters_code%/LC_MESSAGES/%file_name%.po
  - source: /udata_gouvfr/theme/gouvfr/translations/gouvfr.pot.@@
    translation: >-
      /udata_gouvfr/theme/gouvfr/translations/%two_letters_code%/LC_MESSAGES/%file_name%.po
  - source: /theme/js/locales/en.json
    translation: /theme/js/locales/%two_letters_code%.json
